version: '3.8'

services:
  api1:
    image: driels97/rinha-backend-2023-q3-api
    hostname: api1
    ports:
      - "8080:80"
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:aA123456@db:5432/rinhaBackend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2:
    image: driels97/rinha-backend-2023-q3-api
    hostname: api2
    ports:
      - "8081:80"
    expose:
      - "80"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:aA123456@db:5432/rinhaBackend
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'
    
  db:
    image: postgres
    hostname: db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_DB=rinhaBackend
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=aA123456
      - POSTGRES_PORT=5432
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    expose:
      - 5432
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'